// Copyright (c) 2005-2014 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD, an XML Schema to
// C++ data binding compiler.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
// In addition, as a special exception, Code Synthesis Tools CC gives
// permission to link this program with the Xerces-C++ library (or with
// modified versions of Xerces-C++ that use the same license as Xerces-C++),
// and distribute linked combinations including the two. You must obey
// the GNU General Public License version 2 in all respects for all of
// the code used other than Xerces-C++. If you modify this copy of the
// program, you may extend this exception to your version of the program,
// but you are not obligated to do so. If you do not wish to do so, delete
// this exception statement from your version.
//
// Furthermore, Code Synthesis Tools CC makes a special exception for
// the Free/Libre and Open Source Software (FLOSS) which is described
// in the accompanying FLOSSE file.
//

// Begin prologue.
//
#include <DataTablePCH.h>
//
// End prologue.

#include <xsd/cxx/pre.hxx>

#include "position_spawn_table.hxx"

#include <xsd/cxx/xml/dom/parsing-source.hxx>

namespace gdt
{
  // position_spawn_t
  //

  position_spawn_t::
  position_spawn_t ()
  : ::xml_schema::type (),
    entity_code_ (this),
    heading_ (this),
    x_ (this),
    y_ (this),
    z_ (this),
    min_spawn_delay_ (this),
    max_spawn_delay_ (this),
    min_spawn_interval_ (this),
    max_spawn_interval_ (this),
    min_despawn_interval_ (this),
    max_despawn_interval_ (this),
    region_code_ (this),
    entity_path_code_ (this)
  {
  }

  position_spawn_t::
  position_spawn_t (const entity_code_type& entity_code,
                    const heading_type& heading,
                    const x_type& x,
                    const y_type& y,
                    const z_type& z,
                    const min_spawn_delay_type& min_spawn_delay,
                    const max_spawn_delay_type& max_spawn_delay,
                    const min_spawn_interval_type& min_spawn_interval,
                    const max_spawn_interval_type& max_spawn_interval,
                    const min_despawn_interval_type& min_despawn_interval,
                    const max_despawn_interval_type& max_despawn_interval,
                    const region_code_type& region_code,
                    const entity_path_code_type& entity_path_code)
  : ::xml_schema::type (),
    entity_code_ (entity_code, this),
    heading_ (heading, this),
    x_ (x, this),
    y_ (y, this),
    z_ (z, this),
    min_spawn_delay_ (min_spawn_delay, this),
    max_spawn_delay_ (max_spawn_delay, this),
    min_spawn_interval_ (min_spawn_interval, this),
    max_spawn_interval_ (max_spawn_interval, this),
    min_despawn_interval_ (min_despawn_interval, this),
    max_despawn_interval_ (max_despawn_interval, this),
    region_code_ (region_code, this),
    entity_path_code_ (entity_path_code, this)
  {
  }

  position_spawn_t::
  position_spawn_t (const position_spawn_t& x,
                    ::xml_schema::flags f,
                    ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    entity_code_ (x.entity_code_, f, this),
    heading_ (x.heading_, f, this),
    x_ (x.x_, f, this),
    y_ (x.y_, f, this),
    z_ (x.z_, f, this),
    min_spawn_delay_ (x.min_spawn_delay_, f, this),
    max_spawn_delay_ (x.max_spawn_delay_, f, this),
    min_spawn_interval_ (x.min_spawn_interval_, f, this),
    max_spawn_interval_ (x.max_spawn_interval_, f, this),
    min_despawn_interval_ (x.min_despawn_interval_, f, this),
    max_despawn_interval_ (x.max_despawn_interval_, f, this),
    region_code_ (x.region_code_, f, this),
    entity_path_code_ (x.entity_path_code_, f, this)
  {
  }

  position_spawn_t::
  position_spawn_t (const ::xercesc::DOMElement& e,
                    ::xml_schema::flags f,
                    ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    entity_code_ (this),
    heading_ (this),
    x_ (this),
    y_ (this),
    z_ (this),
    min_spawn_delay_ (this),
    max_spawn_delay_ (this),
    min_spawn_interval_ (this),
    max_spawn_interval_ (this),
    min_despawn_interval_ (this),
    max_despawn_interval_ (this),
    region_code_ (this),
    entity_path_code_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< wchar_t > p (e, false, false, true);
      this->parse (p, f);
    }
  }

  void position_spawn_t::
  parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
         ::xml_schema::flags f)
  {
    while (p.more_attributes ())
    {
      const ::xercesc::DOMAttr& i (p.next_attribute ());
      const ::xsd::cxx::xml::qualified_name< wchar_t > n (
        ::xsd::cxx::xml::dom::name< wchar_t > (i));

      if (n.name () == L"entity_code" && n.namespace_ ().empty ())
      {
        this->entity_code_.set (entity_code_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"heading" && n.namespace_ ().empty ())
      {
        this->heading_.set (heading_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"x" && n.namespace_ ().empty ())
      {
        this->x_.set (x_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"y" && n.namespace_ ().empty ())
      {
        this->y_.set (y_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"z" && n.namespace_ ().empty ())
      {
        this->z_.set (z_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"min_spawn_delay" && n.namespace_ ().empty ())
      {
        this->min_spawn_delay_.set (min_spawn_delay_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"max_spawn_delay" && n.namespace_ ().empty ())
      {
        this->max_spawn_delay_.set (max_spawn_delay_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"min_spawn_interval" && n.namespace_ ().empty ())
      {
        this->min_spawn_interval_.set (min_spawn_interval_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"max_spawn_interval" && n.namespace_ ().empty ())
      {
        this->max_spawn_interval_.set (max_spawn_interval_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"min_despawn_interval" && n.namespace_ ().empty ())
      {
        this->min_despawn_interval_.set (min_despawn_interval_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"max_despawn_interval" && n.namespace_ ().empty ())
      {
        this->max_despawn_interval_.set (max_despawn_interval_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"region_code" && n.namespace_ ().empty ())
      {
        this->region_code_.set (region_code_traits::create (i, f, this));
        continue;
      }

      if (n.name () == L"entity_path_code" && n.namespace_ ().empty ())
      {
        this->entity_path_code_.set (entity_path_code_traits::create (i, f, this));
        continue;
      }
    }

    if (!entity_code_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"entity_code",
        L"");
    }

    if (!heading_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"heading",
        L"");
    }

    if (!x_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"x",
        L"");
    }

    if (!y_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"y",
        L"");
    }

    if (!z_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"z",
        L"");
    }

    if (!min_spawn_delay_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"min_spawn_delay",
        L"");
    }

    if (!max_spawn_delay_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"max_spawn_delay",
        L"");
    }

    if (!min_spawn_interval_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"min_spawn_interval",
        L"");
    }

    if (!max_spawn_interval_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"max_spawn_interval",
        L"");
    }

    if (!min_despawn_interval_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"min_despawn_interval",
        L"");
    }

    if (!max_despawn_interval_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"max_despawn_interval",
        L"");
    }

    if (!region_code_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"region_code",
        L"");
    }

    if (!entity_path_code_.present ())
    {
      throw ::xsd::cxx::tree::expected_attribute< wchar_t > (
        L"entity_path_code",
        L"");
    }
  }

  position_spawn_t* position_spawn_t::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class position_spawn_t (*this, f, c);
  }

  position_spawn_t& position_spawn_t::
  operator= (const position_spawn_t& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->entity_code_ = x.entity_code_;
      this->heading_ = x.heading_;
      this->x_ = x.x_;
      this->y_ = x.y_;
      this->z_ = x.z_;
      this->min_spawn_delay_ = x.min_spawn_delay_;
      this->max_spawn_delay_ = x.max_spawn_delay_;
      this->min_spawn_interval_ = x.min_spawn_interval_;
      this->max_spawn_interval_ = x.max_spawn_interval_;
      this->min_despawn_interval_ = x.min_despawn_interval_;
      this->max_despawn_interval_ = x.max_despawn_interval_;
      this->region_code_ = x.region_code_;
      this->entity_path_code_ = x.entity_path_code_;
    }

    return *this;
  }

  position_spawn_t::
  ~position_spawn_t ()
  {
  }

  // position_spawn_table
  //

  position_spawn_table::
  position_spawn_table ()
  : ::xml_schema::type (),
    position_spawn_template_ (this)
  {
  }

  position_spawn_table::
  position_spawn_table (const position_spawn_table& x,
                        ::xml_schema::flags f,
                        ::xml_schema::container* c)
  : ::xml_schema::type (x, f, c),
    position_spawn_template_ (x.position_spawn_template_, f, this)
  {
  }

  position_spawn_table::
  position_spawn_table (const ::xercesc::DOMElement& e,
                        ::xml_schema::flags f,
                        ::xml_schema::container* c)
  : ::xml_schema::type (e, f | ::xml_schema::flags::base, c),
    position_spawn_template_ (this)
  {
    if ((f & ::xml_schema::flags::base) == 0)
    {
      ::xsd::cxx::xml::dom::parser< wchar_t > p (e, true, false, false);
      this->parse (p, f);
    }
  }

  void position_spawn_table::
  parse (::xsd::cxx::xml::dom::parser< wchar_t >& p,
         ::xml_schema::flags f)
  {
    for (; p.more_content (); p.next_content (false))
    {
      const ::xercesc::DOMElement& i (p.cur_element ());
      const ::xsd::cxx::xml::qualified_name< wchar_t > n (
        ::xsd::cxx::xml::dom::name< wchar_t > (i));

      // position_spawn_template
      //
      if (n.name () == L"position_spawn_template" && n.namespace_ ().empty ())
      {
        ::std::unique_ptr< position_spawn_template_type > r (
          position_spawn_template_traits::create (i, f, this));

        this->position_spawn_template_.push_back (::std::move (r));
        continue;
      }

      break;
    }
  }

  position_spawn_table* position_spawn_table::
  _clone (::xml_schema::flags f,
          ::xml_schema::container* c) const
  {
    return new class position_spawn_table (*this, f, c);
  }

  position_spawn_table& position_spawn_table::
  operator= (const position_spawn_table& x)
  {
    if (this != &x)
    {
      static_cast< ::xml_schema::type& > (*this) = x;
      this->position_spawn_template_ = x.position_spawn_template_;
    }

    return *this;
  }

  position_spawn_table::
  ~position_spawn_table ()
  {
  }
}

#include <istream>
#include <xsd/cxx/xml/sax/std-input-source.hxx>
#include <xsd/cxx/tree/error-handler.hxx>

namespace gdt
{
  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (const ::std::wstring& u,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::tree::error_handler< wchar_t > h;

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< wchar_t > (
        u, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< wchar_t > > ();

    return ::std::unique_ptr< ::gdt::position_spawn_table > (
      ::gdt::position_spawn_table_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (const ::std::wstring& u,
                         ::xml_schema::error_handler& h,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< wchar_t > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< wchar_t > ();

    return ::std::unique_ptr< ::gdt::position_spawn_table > (
      ::gdt::position_spawn_table_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (const ::std::wstring& u,
                         ::xercesc::DOMErrorHandler& h,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< wchar_t > (
        u, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< wchar_t > ();

    return ::std::unique_ptr< ::gdt::position_spawn_table > (
      ::gdt::position_spawn_table_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::std::istream& is,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::gdt::position_spawn_table_ (isrc, f, p);
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::std::istream& is,
                         ::xml_schema::error_handler& h,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::gdt::position_spawn_table_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::std::istream& is,
                         ::xercesc::DOMErrorHandler& h,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is);
    return ::gdt::position_spawn_table_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::std::istream& is,
                         const ::std::wstring& sid,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::gdt::position_spawn_table_ (isrc, f, p);
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::std::istream& is,
                         const ::std::wstring& sid,
                         ::xml_schema::error_handler& h,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0,
      (f & ::xml_schema::flags::keep_dom) == 0);

    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::gdt::position_spawn_table_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::std::istream& is,
                         const ::std::wstring& sid,
                         ::xercesc::DOMErrorHandler& h,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::xml::sax::std_input_source isrc (is, sid);
    return ::gdt::position_spawn_table_ (isrc, h, f, p);
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::xercesc::InputSource& i,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xsd::cxx::tree::error_handler< wchar_t > h;

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< wchar_t > (
        i, h, p, f));

    h.throw_if_failed< ::xsd::cxx::tree::parsing< wchar_t > > ();

    return ::std::unique_ptr< ::gdt::position_spawn_table > (
      ::gdt::position_spawn_table_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::xercesc::InputSource& i,
                         ::xml_schema::error_handler& h,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< wchar_t > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< wchar_t > ();

    return ::std::unique_ptr< ::gdt::position_spawn_table > (
      ::gdt::position_spawn_table_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::xercesc::InputSource& i,
                         ::xercesc::DOMErrorHandler& h,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::parse< wchar_t > (
        i, h, p, f));

    if (!d.get ())
      throw ::xsd::cxx::tree::parsing< wchar_t > ();

    return ::std::unique_ptr< ::gdt::position_spawn_table > (
      ::gdt::position_spawn_table_ (
        std::move (d), f | ::xml_schema::flags::own_dom, p));
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (const ::xercesc::DOMDocument& doc,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties& p)
  {
    if (f & ::xml_schema::flags::keep_dom)
    {
      ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
        static_cast< ::xercesc::DOMDocument* > (doc.cloneNode (true)));

      return ::std::unique_ptr< ::gdt::position_spawn_table > (
        ::gdt::position_spawn_table_ (
          std::move (d), f | ::xml_schema::flags::own_dom, p));
    }

    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< wchar_t > n (
      ::xsd::cxx::xml::dom::name< wchar_t > (e));

    if (n.name () == L"position_spawn_table" &&
        n.namespace_ () == L"")
    {
      ::std::unique_ptr< ::gdt::position_spawn_table > r (
        ::xsd::cxx::tree::traits< ::gdt::position_spawn_table, wchar_t >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < wchar_t > (
      n.name (),
      n.namespace_ (),
      L"position_spawn_table",
      L"");
  }

  ::std::unique_ptr< ::gdt::position_spawn_table >
  position_spawn_table_ (::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d,
                         ::xml_schema::flags f,
                         const ::xml_schema::properties&)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > c (
      ((f & ::xml_schema::flags::keep_dom) &&
       !(f & ::xml_schema::flags::own_dom))
      ? static_cast< ::xercesc::DOMDocument* > (d->cloneNode (true))
      : 0);

    ::xercesc::DOMDocument& doc (c.get () ? *c : *d);
    const ::xercesc::DOMElement& e (*doc.getDocumentElement ());

    const ::xsd::cxx::xml::qualified_name< wchar_t > n (
      ::xsd::cxx::xml::dom::name< wchar_t > (e));

    if (f & ::xml_schema::flags::keep_dom)
      doc.setUserData (::xml_schema::dom::tree_node_key,
                       (c.get () ? &c : &d),
                       0);

    if (n.name () == L"position_spawn_table" &&
        n.namespace_ () == L"")
    {
      ::std::unique_ptr< ::gdt::position_spawn_table > r (
        ::xsd::cxx::tree::traits< ::gdt::position_spawn_table, wchar_t >::create (
          e, f, 0));
      return r;
    }

    throw ::xsd::cxx::tree::unexpected_element < wchar_t > (
      n.name (),
      n.namespace_ (),
      L"position_spawn_table",
      L"");
  }
}

#include <ostream>
#include <xsd/cxx/tree/error-handler.hxx>
#include <xsd/cxx/xml/dom/serialization-source.hxx>

namespace gdt
{
  void
  position_spawn_table_ (::std::ostream& o,
                         const ::gdt::position_spawn_table& s,
                         const ::xml_schema::namespace_infomap& m,
                         const ::std::wstring& e,
                         ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::gdt::position_spawn_table_ (s, m, f));

    ::xsd::cxx::tree::error_handler< wchar_t > h;

    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< wchar_t > > ();
    }
  }

  void
  position_spawn_table_ (::std::ostream& o,
                         const ::gdt::position_spawn_table& s,
                         ::xml_schema::error_handler& h,
                         const ::xml_schema::namespace_infomap& m,
                         const ::std::wstring& e,
                         ::xml_schema::flags f)
  {
    ::xsd::cxx::xml::auto_initializer i (
      (f & ::xml_schema::flags::dont_initialize) == 0);

    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::gdt::position_spawn_table_ (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< wchar_t > ();
    }
  }

  void
  position_spawn_table_ (::std::ostream& o,
                         const ::gdt::position_spawn_table& s,
                         ::xercesc::DOMErrorHandler& h,
                         const ::xml_schema::namespace_infomap& m,
                         const ::std::wstring& e,
                         ::xml_schema::flags f)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::gdt::position_spawn_table_ (s, m, f));
    ::xsd::cxx::xml::dom::ostream_format_target t (o);
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< wchar_t > ();
    }
  }

  void
  position_spawn_table_ (::xercesc::XMLFormatTarget& t,
                         const ::gdt::position_spawn_table& s,
                         const ::xml_schema::namespace_infomap& m,
                         const ::std::wstring& e,
                         ::xml_schema::flags f)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::gdt::position_spawn_table_ (s, m, f));

    ::xsd::cxx::tree::error_handler< wchar_t > h;

    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      h.throw_if_failed< ::xsd::cxx::tree::serialization< wchar_t > > ();
    }
  }

  void
  position_spawn_table_ (::xercesc::XMLFormatTarget& t,
                         const ::gdt::position_spawn_table& s,
                         ::xml_schema::error_handler& h,
                         const ::xml_schema::namespace_infomap& m,
                         const ::std::wstring& e,
                         ::xml_schema::flags f)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::gdt::position_spawn_table_ (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< wchar_t > ();
    }
  }

  void
  position_spawn_table_ (::xercesc::XMLFormatTarget& t,
                         const ::gdt::position_spawn_table& s,
                         ::xercesc::DOMErrorHandler& h,
                         const ::xml_schema::namespace_infomap& m,
                         const ::std::wstring& e,
                         ::xml_schema::flags f)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::gdt::position_spawn_table_ (s, m, f));
    if (!::xsd::cxx::xml::dom::serialize (t, *d, e, h, f))
    {
      throw ::xsd::cxx::tree::serialization< wchar_t > ();
    }
  }

  void
  position_spawn_table_ (::xercesc::DOMDocument& d,
                         const ::gdt::position_spawn_table& s,
                         ::xml_schema::flags)
  {
    ::xercesc::DOMElement& e (*d.getDocumentElement ());
    const ::xsd::cxx::xml::qualified_name< wchar_t > n (
      ::xsd::cxx::xml::dom::name< wchar_t > (e));

    if (n.name () == L"position_spawn_table" &&
        n.namespace_ () == L"")
    {
      e << s;
    }
    else
    {
      throw ::xsd::cxx::tree::unexpected_element < wchar_t > (
        n.name (),
        n.namespace_ (),
        L"position_spawn_table",
        L"");
    }
  }

  ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument >
  position_spawn_table_ (const ::gdt::position_spawn_table& s,
                         const ::xml_schema::namespace_infomap& m,
                         ::xml_schema::flags f)
  {
    ::xml_schema::dom::unique_ptr< ::xercesc::DOMDocument > d (
      ::xsd::cxx::xml::dom::serialize< wchar_t > (
        L"position_spawn_table",
        L"",
        m, f));

    ::gdt::position_spawn_table_ (*d, s, f);
    return d;
  }

  void
  operator<< (::xercesc::DOMElement& e, const position_spawn_t& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // entity_code
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"entity_code",
          e));

      a << i.entity_code ();
    }

    // heading
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"heading",
          e));

      a << i.heading ();
    }

    // x
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"x",
          e));

      a << i.x ();
    }

    // y
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"y",
          e));

      a << i.y ();
    }

    // z
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"z",
          e));

      a << i.z ();
    }

    // min_spawn_delay
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"min_spawn_delay",
          e));

      a << i.min_spawn_delay ();
    }

    // max_spawn_delay
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"max_spawn_delay",
          e));

      a << i.max_spawn_delay ();
    }

    // min_spawn_interval
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"min_spawn_interval",
          e));

      a << i.min_spawn_interval ();
    }

    // max_spawn_interval
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"max_spawn_interval",
          e));

      a << i.max_spawn_interval ();
    }

    // min_despawn_interval
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"min_despawn_interval",
          e));

      a << i.min_despawn_interval ();
    }

    // max_despawn_interval
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"max_despawn_interval",
          e));

      a << i.max_despawn_interval ();
    }

    // region_code
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"region_code",
          e));

      a << i.region_code ();
    }

    // entity_path_code
    //
    {
      ::xercesc::DOMAttr& a (
        ::xsd::cxx::xml::dom::create_attribute (
          L"entity_path_code",
          e));

      a << i.entity_path_code ();
    }
  }

  void
  operator<< (::xercesc::DOMElement& e, const position_spawn_table& i)
  {
    e << static_cast< const ::xml_schema::type& > (i);

    // position_spawn_template
    //
    for (position_spawn_table::position_spawn_template_const_iterator
         b (i.position_spawn_template ().begin ()), n (i.position_spawn_template ().end ());
         b != n; ++b)
    {
      ::xercesc::DOMElement& s (
        ::xsd::cxx::xml::dom::create_element (
          L"position_spawn_template",
          e));

      s << *b;
    }
  }
}

#include <xsd/cxx/post.hxx>

// Begin epilogue.
//
//
// End epilogue.

